import { IdSizePreset } from '../types';

export const ID_SIZE_PRESETS: IdSizePreset[] = [
  {
    id: '2x2',
    name: '2" x 2" (50.8 x 50.8 mm)',
    widthMm: 50.8,
    heightMm: 50.8,
    description: 'Universal standard 2x2 inch square ID photo',
    category: 'standard',
    popularFor: 'US Passport, US Visa, PH Passport/PRC/NBI, India OCI, Board Exams',
  },
  {
    id: '1x1',
    name: '1" x 1" (25.4 x 25.4 mm)',
    widthMm: 25.4,
    heightMm: 25.4,
    description: 'Compact 1x1 inch square photo',
    category: 'standard',
    popularFor: 'School IDs, Philippine Clearances, Resume & Job Applications',
  },
  {
    id: 'passport_schengen',
    name: '35 x 45 mm (Passport/Schengen)',
    widthMm: 35,
    heightMm: 45,
    description: 'Standard International ICAO / European format',
    category: 'passport',
    popularFor: 'UK Passport, Schengen Visa, Australia, Canada, Singapore, New Zealand',
  },
  {
    id: 'visa_asia',
    name: '45 x 45 mm (Japan/Korea Visa)',
    widthMm: 45,
    heightMm: 45,
    description: 'East Asian standard visa photo size',
    category: 'passport',
    popularFor: 'Japan Tourist Visa, South Korea Visa, Taiwan Visa',
  },
  {
    id: 'cr80_badge',
    name: '85.6 x 54 mm (CR80 ID Badge)',
    widthMm: 85.6,
    heightMm: 54,
    description: 'Credit Card / Lanyard Badge standard format',
    category: 'badge',
    popularFor: 'Company Staff Pass, Student ID Card, Conference Badge, Membership',
  },
  {
    id: 'wallet_photo',
    name: '50 x 70 mm (Wallet / 2" x 2.75")',
    widthMm: 50,
    heightMm: 70,
    description: 'Medium portrait format for keepsake & wallets',
    category: 'standard',
    popularFor: 'Wallet Portraits, High School Graduation, Keepsakes',
  },
  {
    id: 'custom_combo',
    name: 'Custom Mix & Match (e.g. 2x2 + 1x1)',
    widthMm: 50.8,
    heightMm: 50.8,
    description: 'Customize how many 2x2, 1x1, passport, or visa photos on a single page',
    category: 'combo',
    popularFor: 'Personalized mix: choose custom quantities of 2x2, 1x1, passport & visa',
    comboItems: [
      { id: '2x2', widthMm: 50.8, heightMm: 50.8, label: '2" x 2" (50.8 × 50.8 mm)', count: 4 },
      { id: '1x1', widthMm: 25.4, heightMm: 25.4, label: '1" x 1" (25.4 × 25.4 mm)', count: 8 },
    ],
  },
  {
    id: 'combo_all_in_one',
    name: 'Combo Value Pack (4x 2"x2" + 8x 1"x1")',
    widthMm: 50.8,
    heightMm: 50.8,
    description: 'Most requested printing shop bundle on a single page',
    category: 'combo',
    popularFor: 'Job applications, government clearance packages, school enrollment',
    comboItems: [
      { id: '2x2', widthMm: 50.8, heightMm: 50.8, label: '2" x 2" (50.8 × 50.8 mm)', count: 4 },
      { id: '1x1', widthMm: 25.4, heightMm: 25.4, label: '1" x 1" (25.4 × 25.4 mm)', count: 8 },
    ],
  },
  {
    id: 'combo_visa_mix',
    name: 'Visa Pack (4x 35x45mm + 4x 2"x2")',
    widthMm: 35,
    heightMm: 45,
    description: 'Dual travel visa package for international trips',
    category: 'combo',
    popularFor: 'Frequent flyers, US + Schengen multi-country visa filings',
    comboItems: [
      { id: 'passport_schengen', widthMm: 35, heightMm: 45, label: '35 × 45 mm Schengen', count: 4 },
      { id: '2x2', widthMm: 50.8, heightMm: 50.8, label: '2" x 2" US Visa', count: 4 },
    ],
  },
  {
    id: 'custom',
    name: 'Custom Dimensions',
    widthMm: 50,
    heightMm: 50,
    description: 'Specify your exact custom millimeters or inches',
    category: 'standard',
    popularFor: 'Specialty permits, unique badges, license photos',
  },
];

export const PAPER_DIMENSIONS = {
  a4: {
    name: 'A4',
    widthMm: 210,
    heightMm: 297,
    description: 'Standard International paper size (210 x 297 mm)',
  },
  letter: {
    name: 'US Letter',
    widthMm: 215.9,
    heightMm: 279.4,
    description: 'Standard North American paper size (8.5 x 11 in)',
  },
  '3r': {
    name: '3R (3.5" x 5")',
    widthMm: 89,
    heightMm: 127,
    description: 'Small snapshot / wallet photo size (89 x 127 mm)',
  },
  '4r': {
    name: '4R (4" x 6")',
    widthMm: 102,
    heightMm: 152,
    description: 'Most popular standard snapshot size (102 x 152 mm)',
  },
  '5r': {
    name: '5R (5" x 7")',
    widthMm: 127,
    heightMm: 178,
    description: 'Medium portrait size, commonly framed (127 x 178 mm)',
  },
  '8r': {
    name: '8R (8" x 10")',
    widthMm: 203,
    heightMm: 254,
    description: 'Standard enlargement / formal portrait (203 x 254 mm)',
  },
};
